export const logo = require('../../assets/images/logo.png')
export const background = require('../../assets/images/background.png')
export const banner1 = require('../../assets/images/banner1.jpg')
export const banner2 = require('../../assets/images/banner2.jpg')
export const banner3 = require('../../assets/images/banner3.jpg')
